create table public.test_sessions (
  pin text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_active boolean default true,
  status text default 'WAITING'
);
create table public.exam_results (
  id bigint generated by default as identity primary key,
  test_pin text references public.test_sessions(pin) on delete cascade not null,
  student_name text not null,
  score integer default 0,
  level integer default 1,
  started_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(test_pin, student_name),
  status text default 'APPROVED'
);
alter table public.test_sessions enable row level security;
alter table public.exam_results enable row level security;
create policy "Enable all access for all users" on public.test_sessions
for all using (true) with check (true);
create policy "Enable all access for all users" on public.exam_results
for all using (true) with check (true);
